
### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1996-07-08",
  "email": "ceh201312@naver.com",
  "name": "myname",
  "password": "pw",
  "phone": "01000000000"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=ceh201312@naver.com&code=AORUi4Rqds

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "ceh201312@naver.com",
  "password": "pw"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1dnl3WTg3MW0rMUxZNUVQMFBrSlhlUW4wSGVzMUV5RFdPS3JzdlRobW00PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTM4NDgsImV4cCI6MTY4MDQ0MDI0OH0.RpH1vk8az1IwXQQgHmdx1-HjSPY1oF9dIjuopRXAiLc

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1dnl3WTg3MW0rMUxZNUVQMFBrSlhlUW4wSGVzMUV5RFdPS3JzdlRobW00PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAzNTM4NDgsImV4cCI6MTY4MDQ0MDI0OH0.RpH1vk8az1IwXQQgHmdx1-HjSPY1oF9dIjuopRXAiLc

{
  "from": "server",
  "message": "돈 충전",
  "money": 100000
}

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1996-07-08",
  "email": "ceh201312@naver.com",
  "name": "myname1",
  "password": "pw1",
  "phone": "01000000000"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify?email=ceh201312@naver.com&code=lc7Gqbtbue

### 로그인 (셀러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "ceh201312@naver.com",
  "password": "pw1"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1dnl3WTg3MW0rMUxZNUVQMFBrSlhlUW4wSGVzMUV5RFdPS3JzdlRobW00PSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMTc5OTU0LCJleHAiOjE2ODAyNjYzNTR9.I_5Eg5le_2zgGvacPUI7JAlKJGnSZxd3AuzQlWJ_Mg8